/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package grammar.usecase;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.*;
import grammar.model.ConceptModel;

public class ConceptUsecaseTest {
    @Test public void testAppHasAGreeting() {
        ConceptUsecase classUnderTest = new SampleConceptUsecase();
        List<ConceptModel> result = classUnderTest.conceptsByTagName("동사");
        
        assertEquals(3, result.size());

        List<ConceptModel> sample = getConceptModelSamples();
    
        boolean isSameArrayContent = Arrays.deepEquals(result.toArray(), sample.toArray());
        assertTrue(isSameArrayContent);
    }

    private List<ConceptModel> getConceptModelSamples() {

        ConceptModel d1 = new ConceptModel(
            "동사 vs 명사",
            "동사 명사에 대한 설명입니다.",
            new String[] {"동사", "명사"}
        );

        ConceptModel d2 = new ConceptModel(
            "동사 vs 명사",
            "동사 명사에 대한 설명입니다.",
            new String[] {"동사", "명사"}
        );

        ConceptModel d3 = new ConceptModel(
            "동사 vs 명사",
            "동사 명사에 대한 설명입니다.",
            new String[] {"동사", "명사"}
        );

        List<ConceptModel> rv = new ArrayList<>();
        rv.add(d1);
        rv.add(d2);
        rv.add(d3);

        return rv;
    }
}
